//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SensorMeter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public long MessageID { get; set; }
        public string JobDetailID { get; set; }
        public Nullable<decimal> Pressure { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
    }
}
