//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SensorMeter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tank
    {
        public int TankID { get; set; }
        public int CompartmentID { get; set; }
        public string TankCode { get; set; }
        public string TankName { get; set; }
        public string TankDescription { get; set; }
        public int NumCompartment { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModifyDate { get; set; }
    
        public virtual Compartment Compartment { get; set; }
    }
}
